default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  # Optional (sometimes helpful on managed PG):
  # prepared_statements: false
  # variables:
  #   statement_timeout: 15000

development:
  <<: *default
  database: pumanawa_kam_development
  username: <%= ENV.fetch("PUMANAWA_DEV_USR", "postgres") %>
  password: <%= ENV.fetch("PUMANAWA_KAM_DEV_PWD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

test:
  <<: *default
  database: pumanawa_kam_test
  username: <%= ENV.fetch("PUMANAWA_TEST_USR", "postgres") %>
  password: <%= ENV.fetch("PUMANAWA_KAM_TEST_PWD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    # URL-only for Render. Render injects this automatically when linked.
    url: <%= ENV.fetch("DATABASE_URL") %>
